version: '3.9'

services:
  web:
    build: .
    container_name: habbit-web
    env_file: .env
    ports:
      - "3005:3000"
    depends_on:
      - db
      - redis
    command: ["/bin/sh", "-c", "npm run prisma:generate && npm run prisma:migrate && npm start"]
  db:
    image: postgres:16
    container_name: habbit-db
    environment:
      POSTGRES_DB: habbit
      POSTGRES_USER: habbit
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - habbit_db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: habbit-redis

volumes:
  habbit_db:
