name: Deploy Generic Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service folder name (also remote directory name)'
        required: true
      source_path:
        description: 'Path in repo to deploy (e.g. n8n or my-app)'
        required: true
      server_host:
        description: 'Target host (SSH host from config)'
        required: true
        default: 'n8n'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/deploy-docker-compose
        with:
          server_host: ${{ inputs.server_host }}
          service_name: ${{ inputs.service_name }}
          source_path: ${{ inputs.source_path }}
          server_username: ${{ secrets.DEFAULT_SSH_USER }}
          server_port: ${{ secrets.DEFAULT_SSH_PORT }}
          server_ssh_key: ${{ secrets.DEFAULT_SSH_KEY }}
