name: Deploy Habbit

on:
  push:
    branches: [ main ]
    paths:
      - 'habbit/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      SERVICE_NAME: 'habbit'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/deploy-docker-compose
        with:
          server_host: 'n8n'
          service_name: ${{ env.SERVICE_NAME }}
          source_path: ${{ env.SERVICE_NAME }}
          server_username: ${{ secrets.DEFAULT_SSH_USER }}
          server_port: ${{ secrets.DEFAULT_SSH_PORT }}
          server_ssh_key: ${{ secrets.DEFAULT_SSH_KEY }}
